name: AAMMN
description: The African American Male Mathematics Network (AAMMN) is a collective network whose primary mission is to encourage, support, and empower African American men who have an interest in mathematics and mathematics-intensive fields to fulfill, achieve, and thrive in their mathematics-related aspirations. 


sass:
  style: uncompressed